name: doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  docs:
    name: "generate docs for GisL"
    runs-on: "ubuntu-20.04"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev gdal-bin build-essential gmt
          export C_INCLUDE_PATH=/usr/include/gdal:$C_INCLUDE_PATH
          export CPLUS_INCLUDE_PATH=/usr/include/gdal:$CPLUS_INCLUDE_PATH
          sudo ldconfig

      - name: Install eigen
        run: |
          sudo apt-get update
          sudo apt-get install libeigen3-dev

      - name: Install doxygen
        run: |
          sudo apt-get install doxygen-latex doxygen graphviz
          sudo su
          pip install sphinx breathe

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build docs
        run: |
          mkdir build
          cmake -B build -S .
          cmake --build build --target docs
          cmake --build build --target sphinx_docs